# Generated by Django 3.2.6 on 2021-08-11 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_birthdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='birthdat',
            new_name='birthday',
        ),
    ]
